export const REDIS_CLIENT_TOKEN = 'REDIS_CLIENT';
export const CACHE_PREFIX_TOKEN = 'CACHE_PREFIX';
export const CACHE_KEY_TOKEN = 'CACHE_KEY';
export const INVALIDATE_CACHE_TOKEN = 'INVALIDATE_CACHE';
